//Skill
export const CREATE_SKILL = "CREATE_SKILL"
export const CREATE_SKILL_RED = "CREATE_SKILL_RED"
export const GET_SKILL = "GET_SKILL"
export const GET_SKILL_RED = "GET_SKILL_RED"
export const UPDATE_SKILL = "UPDATE_SKILL"
export const UPDATE_SKILL_RED = "UPDATE_SKILL_RED"
export const DELETE_SKILL = "DELETE_SKILL"
export const DELETE_SKILL_RED = "DELETE_SKILL_RED"


//PORTFOLIO
export const CREATE_PORTFOLIO = "CREATE_PORTFOLIO"
export const CREATE_PORTFOLIO_RED = "CREATE_PORTFOLIO_RED"
export const GET_PORTFOLIO = "GET_PORTFOLIO"
export const GET_PORTFOLIO_RED = "GET_PORTFOLIO_RED"
export const UPDATE_PORTFOLIO = "UPDATE_PORTFOLIO"
export const UPDATE_PORTFOLIO_RED = "UPDATE_PORTFOLIO_RED"
export const DELETE_PORTFOLIO = "DELETE_PORTFOLIO"
export const DELETE_PORTFOLIO_RED = "DELETE_PORTFOLIO_RED"


//CERTIFICATE
export const CREATE_CERTIFICATE = "CREATE_CERTIFICATE"
export const CREATE_CERTIFICATE_RED = "CREATE_CERTIFICATE_RED"
export const GET_CERTIFICATE = "GET_CERTIFICATE"
export const GET_CERTIFICATE_RED = "GET_CERTIFICATE_RED"
export const UPDATE_CERTIFICATE = "UPDATE_CERTIFICATE"
export const UPDATE_CERTIFICATE_RED = "UPDATE_CERTIFICATE_RED"
export const DELETE_CERTIFICATE = "DELETE_CERTIFICATE"
export const DELETE_CERTIFICATE_RED = "DELETE_CERTIFICATE_RED"


//EDUCATION
export const CREATE_EDUCATION = "CREATE_EDUCATION"
export const CREATE_EDUCATION_RED = "CREATE_EDUCATION_RED"
export const GET_EDUCATION = "GET_EDUCATION"
export const GET_EDUCATION_RED = "GET_EDUCATION_RED"
export const UPDATE_EDUCATION = "UPDATE_EDUCATION"
export const UPDATE_EDUCATION_RED = "UPDATE_EDUCATION_RED"
export const DELETE_EDUCATION = "DELETE_EDUCATION"
export const DELETE_EDUCATION_RED = "DELETE_EDUCATION_RED"


//EXPERIENCE
export const CREATE_EXPERIENCE = "CREATE_EXPERIENCE"
export const CREATE_EXPERIENCE_RED = "CREATE_EXPERIENCE_RED"
export const GET_EXPERIENCE = "GET_EXPERIENCE"
export const GET_EXPERIENCE_RED = "GET_EXPERIENCE_RED"
export const UPDATE_EXPERIENCE = "UPDATE_EXPERIENCE"
export const UPDATE_EXPERIENCE_RED = "UPDATE_EXPERIENCE_RED"
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE"
export const DELETE_EXPERIENCE_RED = "DELETE_EXPERIENCE_RED"

//SERVICE
export const CREATE_SERVICE = "CREATE_SERVICE"
export const CREATE_SERVICE_RED = "CREATE_SERVICE_RED"
export const GET_SERVICE = "GET_SERVICE"
export const GET_SERVICE_RED = "GET_SERVICE_RED"
export const UPDATE_SERVICE = "UPDATE_SERVICE"
export const UPDATE_SERVICE_RED = "UPDATE_SERVICE_RED"
export const DELETE_SERVICE = "DELETE_SERVICE"
export const DELETE_SERVICE_RED = "DELETE_SERVICE_RED"

//TESTIMONIAL
export const CREATE_TESTIMONIAL = "CREATE_TESTIMONIAL"
export const CREATE_TESTIMONIAL_RED = "CREATE_TESTIMONIAL_RED"
export const GET_TESTIMONIAL = "GET_TESTIMONIAL"
export const GET_TESTIMONIAL_RED = "GET_TESTIMONIAL_RED"
export const UPDATE_TESTIMONIAL = "UPDATE_TESTIMONIAL"
export const UPDATE_TESTIMONIAL_RED = "UPDATE_TESTIMONIAL_RED"
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL"
export const DELETE_TESTIMONIAL_RED = "DELETE_TESTIMONIAL_RED"


//Contact Us
export const CREATE_CONTACT_US = "CREATE_CONTACT_US"
export const CREATE_CONTACT_US_RED = "CREATE_CONTACT_US_RED"
export const GET_CONTACT_US = "GET_CONTACT_US"
export const GET_CONTACT_US_RED = "GET_CONTACT_US_RED"
export const UPDATE_CONTACT_US = "UPDATE_CONTACT_US"
export const UPDATE_CONTACT_US_RED = "UPDATE_CONTACT_US_RED"
export const DELETE_CONTACT_US = "DELETE_CONTACT_US"
export const DELETE_CONTACT_US_RED = "DELETE_CONTACT_US_RED"
